#!/bin/zsh

##? Autoload function files in directory
#function autoload-dir {
  local zdir
  local -a zautoloads
  for zdir in $@; do
    [[ -n "$zdir" ]] || continue
    if [[ ! -d $zdir ]]; then
      echo >&2 "autoload-dir: Directory not found '$zdir'."
      return 1
    fi
    fpath=("$zdir" $fpath)
    zautoloads=($zdir/*~_*(N.:t))
    (( $#zautoloads > 0 )) && autoload -Uz $zautoloads
  done
#}
