#!/bin/zsh
#function plugin-load {
  : ${REPO_HOME:=${XDG_CACHE_HOME:-$HOME/.cache}/repos}
  local plugin inits=()
  for plugin in $@; do
    inits=(
      {$ZSH_CUSTOM,$ZSH}/plugins/$plugin/${plugin}.plugin.zsh(N)
      $REPO_HOME/$plugin/${plugin:t}.plugin.zsh(N)
      $REPO_HOME/$plugin/*.{plugin.zsh,zsh,zsh-theme}(N)
    )
    if ! (( $#inits )); then
      echo >&2 "plugin-load: Plugin not found '$1'."
      continue
    fi
    source $inits[1]
  done
#}
