#!/bin/zsh
if [[ -n "$1" ]]; then
  local -a configs=(${ZDOTDIR:-$HOME/.config/zsh}/themes/$1.p10k.zsh(N))
  (( $#configs )) && source $configs[1]
fi
source ${ZSH_REPO_HOME}/romkatv/powerlevel10k/powerlevel10k.zsh-theme
