#!/bin/zsh

# function zsh_custom {
emulate -L zsh
setopt local_options

local subcmd=$1 plugin_dir plugin loaded
if [[ "$subcmd" == list ]]; then
  for plugin_dir in $ZSH_CUSTOM/plugins/*(N); do
    echo ${plugin_dir:t}
  done
elif [[ "$subcmd" == loaded ]]; then
  for plugin_dir in $ZSH_CUSTOM/plugins/*(N); do
    plugin=${plugin_dir:t}
    if zstyle -t ":zsh_custom:plugin:${plugin}" "loaded"; then
      loaded=yes
    else
      loaded=no
    fi
    printf '%-25s %s\n' $plugin $loaded
  done
elif [[ "$subcmd" == zprof ]]; then
  zstyle -L \
  | awk '
    $1 == "zstyle" && $3 == "load_time" {
      ctx = $2
      time = $4

      n = split(ctx, parts, ":")
      name = parts[n]

      printf "%-30s %s\n", name, time
    }
  ' \
  | sort -k2,2gr
else
  echo "Unrecognized subcommand '$subcmd'." >&2
  return 1
fi
# }
