#!/bin/zsh
0=${(%):-%x}

if ! (( $+commands[starship] )); then
  if (( $+commands[brew] )); then
    command brew install starship
  else
    echo >&2 "Starship prompt not installed. See https://starship.rs"
    return 1
  fi
fi

# Set the config
zstyle -s ':zsh_custom:plugin:prompt' config _prompt_config
if [[ -n "$_prompt_config" ]]; then
  _prompt_config=${0:A:h:h}/themes/${_prompt_config}.toml
  [[ -f $_prompt_config ]] && export STARSHIP_CONFIG=$_prompt_config
fi
unset _prompt_config

#eval "$(starship init zsh)"
source <(starship init zsh --print-full-init)

# vim: ft=zsh sw=2 ts=2 et
