#!/bin/zsh

# Make starship work with built-in prompt system.
#function prompt_starship_setup {
# When loaded through the prompt command, these prompt_* options will be enabled
prompt_opts=(cr percent sp subst)

# Set the starship config based on the argument if provided.
if [[ -n "$1" ]]; then
  local -a configs=(
    "${ZDOTDIR:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh}/themes/${1}.toml"(N)
    "${XDG_CONFIG_HOME:-$HOME/.config}/starship/${1}.toml"(N)
    "$MY_ZSH_CUSTOM/themes/${1}.toml"(N)
  )
  (( $#configs )) && export STARSHIP_CONFIG=$configs[1]
fi

# Initialize starship.
if zstyle -t ':zsh_custom:init:prompt' 'use-cache'; then
  cached-eval 'starship-init-zsh' starship init zsh
else
  source <(starship init zsh)
fi
#}
