#!/bin/zsh
0=${(%):-%x}

# Set the config
zstyle -s ':zsh_custom:plugin:prompt' config _prompt_config
if [[ -n "$_prompt_config" ]]; then
  _prompt_config=${0:A:h:h}/themes/${_prompt_config}.p10k.zsh
else
  _prompt_config=${ZDOTDIR:-$HOME}/.p10k.zsh
fi

# To customize prompt, run `p10k configure` or edit ${ZDOTDIR:-~}/.p10k.zsh.
[[ -f $_prompt_config ]] && source $_prompt_config
#unset _prompt_config

plugin-load romkatv/powerlevel10k
