#!/bin/zsh
antibody bundle romkatv/powerlevel10k
if [[ -n "$1" ]]; then
  local -a configs=(
    ${ZDOTDIR:-$HOME/.config/zsh}/themes/$1.p10k.zsh(N)
    $MY_ZSH_CUSTOM/themes/$1.p10k.zsh(N)
  )
  (( $#configs )) && source $configs[1]
fi
