#!/bin/zsh
#function prompt_pwd {
  setopt local_options extended_glob

  local cur_pwd="${PWD/#$HOME/~}"
  local MATCH result

  if [[ "$cur_pwd" == (#m)[/~] ]]; then
    result="$MATCH"
  elif zstyle -m ':zsh_custom:plugin:prompt' pwd-length 'full'; then
    result=${PWD}
  elif zstyle -m ':zsh_custom:plugin:prompt' pwd-length 'long'; then
    result=${cur_pwd}
  else
    result="${${${${(@j:/:M)${(@s:/:)cur_pwd}##.#?}:h}%/}//\%/%%}/${${cur_pwd:t}//\%/%%}"
  fi

  print -r -- "$result"
#}
